package klutch.hitter.com.model;

import java.util.Date;

public class Comment {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.cwriter
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	private String cwriter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.cmt
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	private String cmt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.no
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	private Integer no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.cno
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	private Integer cno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.cmtdate
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	private Date cmtdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column comment.cmtip
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	private String cmtip;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.cwriter
	 * @return  the value of comment.cwriter
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public String getCwriter() {
		return cwriter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.cwriter
	 * @param cwriter  the value for comment.cwriter
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public void setCwriter(String cwriter) {
		this.cwriter = cwriter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.cmt
	 * @return  the value of comment.cmt
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public String getCmt() {
		return cmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.cmt
	 * @param cmt  the value for comment.cmt
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public void setCmt(String cmt) {
		this.cmt = cmt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.no
	 * @return  the value of comment.no
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public Integer getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.no
	 * @param no  the value for comment.no
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public void setNo(Integer no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.cno
	 * @return  the value of comment.cno
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public Integer getCno() {
		return cno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.cno
	 * @param cno  the value for comment.cno
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public void setCno(Integer cno) {
		this.cno = cno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.cmtdate
	 * @return  the value of comment.cmtdate
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public Date getCmtdate() {
		return cmtdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.cmtdate
	 * @param cmtdate  the value for comment.cmtdate
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public void setCmtdate(Date cmtdate) {
		this.cmtdate = cmtdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column comment.cmtip
	 * @return  the value of comment.cmtip
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public String getCmtip() {
		return cmtip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column comment.cmtip
	 * @param cmtip  the value for comment.cmtip
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	public void setCmtip(String cmtip) {
		this.cmtip = cmtip;
	}
}