package klutch.hitter.com.model;

import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

public class Members {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memid
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String memid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.mempass
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String mempass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.mememail
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String mememail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memphone
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String memphone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memaddress
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String memaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memgender
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String memgender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memname
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String memname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.membirthday
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String membirthday;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.mempicture
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String mempicture;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memdate
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private Date memdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column members.memip
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String memip;
	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memid
	 * @return  the value of members.memid
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMemid() {
		return memid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memid
	 * @param memid  the value for members.memid
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemid(String memid) {
		this.memid = memid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.mempass
	 * @return  the value of members.mempass
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMempass() {
		return mempass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.mempass
	 * @param mempass  the value for members.mempass
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMempass(String mempass) {
		this.mempass = mempass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.mememail
	 * @return  the value of members.mememail
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMememail() {
		return mememail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.mememail
	 * @param mememail  the value for members.mememail
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMememail(String mememail) {
		this.mememail = mememail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memphone
	 * @return  the value of members.memphone
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMemphone() {
		return memphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memphone
	 * @param memphone  the value for members.memphone
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemphone(String memphone) {
		this.memphone = memphone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memaddress
	 * @return  the value of members.memaddress
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMemaddress() {
		return memaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memaddress
	 * @param memaddress  the value for members.memaddress
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemaddress(String memaddress) {
		this.memaddress = memaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memgender
	 * @return  the value of members.memgender
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMemgender() {
		return memgender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memgender
	 * @param memgender  the value for members.memgender
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemgender(String memgender) {
		this.memgender = memgender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memname
	 * @return  the value of members.memname
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMemname() {
		return memname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memname
	 * @param memname  the value for members.memname
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemname(String memname) {
		this.memname = memname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.membirthday
	 * @return  the value of members.membirthday
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMembirthday() {
		return membirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.membirthday
	 * @param membirthday  the value for members.membirthday
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMembirthday(String membirthday) {
		this.membirthday = membirthday;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.mempicture
	 * @return  the value of members.mempicture
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMempicture() {
		return mempicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.mempicture
	 * @param mempicture  the value for members.mempicture
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMempicture(String mempicture) {
		this.mempicture = mempicture;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memdate
	 * @return  the value of members.memdate
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Date getMemdate() {
		return memdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memdate
	 * @param memdate  the value for members.memdate
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemdate(Date memdate) {
		this.memdate = memdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column members.memip
	 * @return  the value of members.memip
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getMemip() {
		return memip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column members.memip
	 * @param memip  the value for members.memip
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setMemip(String memip) {
		this.memip = memip;
	}

	private int memphone1;
	public int getMemphone1() {
		return memphone1;
	}

	public void setMemphone1(int memphone1) {
		this.memphone1 = memphone1;
	}

	public int getMemphone2() {
		return memphone2;
	}

	public void setMemphone2(int memphone2) {
		this.memphone2 = memphone2;
	}

	public int getMemphone3() {
		return memphone3;
	}

	public void setMemphone3(int memphone3) {
		this.memphone3 = memphone3;
	}

	private int memphone2;
	private int memphone3;
	
	
	private int membirthday1;
	private int membirthday2;
	private int membirthday3;
	
	private String mememail1;
	private String mememail2;

	public int getMembirthday1() {
		return membirthday1;
	}

	public void setMembirthday1(int membirthday1) {
		this.membirthday1 = membirthday1;
	}

	public int getMembirthday2() {
		return membirthday2;
	}

	public void setMembirthday2(int membirthday2) {
		this.membirthday2 = membirthday2;
	}

	public int getMembirthday3() {
		return membirthday3;
	}

	public void setMembirthday3(int membirthday3) {
		this.membirthday3 = membirthday3;
	}

	public String getMememail1() {
		return mememail1;
	}

	public void setMememail1(String mememail1) {
		this.mememail1 = mememail1;
	}

	public String getMememail2() {
		return mememail2;
	}

	public void setMememail2(String mememail2) {
		this.mememail2 = mememail2;
	}	
	
}