package klutch.hitter.com.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MembersExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public MembersExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andMemidIsNull() {
			addCriterion("memid is null");
			return (Criteria) this;
		}

		public Criteria andMemidIsNotNull() {
			addCriterion("memid is not null");
			return (Criteria) this;
		}

		public Criteria andMemidEqualTo(String value) {
			addCriterion("memid =", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidNotEqualTo(String value) {
			addCriterion("memid <>", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidGreaterThan(String value) {
			addCriterion("memid >", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidGreaterThanOrEqualTo(String value) {
			addCriterion("memid >=", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidLessThan(String value) {
			addCriterion("memid <", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidLessThanOrEqualTo(String value) {
			addCriterion("memid <=", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidLike(String value) {
			addCriterion("memid like", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidNotLike(String value) {
			addCriterion("memid not like", value, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidIn(List<String> values) {
			addCriterion("memid in", values, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidNotIn(List<String> values) {
			addCriterion("memid not in", values, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidBetween(String value1, String value2) {
			addCriterion("memid between", value1, value2, "memid");
			return (Criteria) this;
		}

		public Criteria andMemidNotBetween(String value1, String value2) {
			addCriterion("memid not between", value1, value2, "memid");
			return (Criteria) this;
		}

		public Criteria andMempassIsNull() {
			addCriterion("mempass is null");
			return (Criteria) this;
		}

		public Criteria andMempassIsNotNull() {
			addCriterion("mempass is not null");
			return (Criteria) this;
		}

		public Criteria andMempassEqualTo(String value) {
			addCriterion("mempass =", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassNotEqualTo(String value) {
			addCriterion("mempass <>", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassGreaterThan(String value) {
			addCriterion("mempass >", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassGreaterThanOrEqualTo(String value) {
			addCriterion("mempass >=", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassLessThan(String value) {
			addCriterion("mempass <", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassLessThanOrEqualTo(String value) {
			addCriterion("mempass <=", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassLike(String value) {
			addCriterion("mempass like", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassNotLike(String value) {
			addCriterion("mempass not like", value, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassIn(List<String> values) {
			addCriterion("mempass in", values, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassNotIn(List<String> values) {
			addCriterion("mempass not in", values, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassBetween(String value1, String value2) {
			addCriterion("mempass between", value1, value2, "mempass");
			return (Criteria) this;
		}

		public Criteria andMempassNotBetween(String value1, String value2) {
			addCriterion("mempass not between", value1, value2, "mempass");
			return (Criteria) this;
		}

		public Criteria andMememailIsNull() {
			addCriterion("mememail is null");
			return (Criteria) this;
		}

		public Criteria andMememailIsNotNull() {
			addCriterion("mememail is not null");
			return (Criteria) this;
		}

		public Criteria andMememailEqualTo(String value) {
			addCriterion("mememail =", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailNotEqualTo(String value) {
			addCriterion("mememail <>", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailGreaterThan(String value) {
			addCriterion("mememail >", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailGreaterThanOrEqualTo(String value) {
			addCriterion("mememail >=", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailLessThan(String value) {
			addCriterion("mememail <", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailLessThanOrEqualTo(String value) {
			addCriterion("mememail <=", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailLike(String value) {
			addCriterion("mememail like", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailNotLike(String value) {
			addCriterion("mememail not like", value, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailIn(List<String> values) {
			addCriterion("mememail in", values, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailNotIn(List<String> values) {
			addCriterion("mememail not in", values, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailBetween(String value1, String value2) {
			addCriterion("mememail between", value1, value2, "mememail");
			return (Criteria) this;
		}

		public Criteria andMememailNotBetween(String value1, String value2) {
			addCriterion("mememail not between", value1, value2, "mememail");
			return (Criteria) this;
		}

		public Criteria andMemphoneIsNull() {
			addCriterion("memphone is null");
			return (Criteria) this;
		}

		public Criteria andMemphoneIsNotNull() {
			addCriterion("memphone is not null");
			return (Criteria) this;
		}

		public Criteria andMemphoneEqualTo(String value) {
			addCriterion("memphone =", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneNotEqualTo(String value) {
			addCriterion("memphone <>", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneGreaterThan(String value) {
			addCriterion("memphone >", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneGreaterThanOrEqualTo(String value) {
			addCriterion("memphone >=", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneLessThan(String value) {
			addCriterion("memphone <", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneLessThanOrEqualTo(String value) {
			addCriterion("memphone <=", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneLike(String value) {
			addCriterion("memphone like", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneNotLike(String value) {
			addCriterion("memphone not like", value, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneIn(List<String> values) {
			addCriterion("memphone in", values, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneNotIn(List<String> values) {
			addCriterion("memphone not in", values, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneBetween(String value1, String value2) {
			addCriterion("memphone between", value1, value2, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemphoneNotBetween(String value1, String value2) {
			addCriterion("memphone not between", value1, value2, "memphone");
			return (Criteria) this;
		}

		public Criteria andMemaddressIsNull() {
			addCriterion("memaddress is null");
			return (Criteria) this;
		}

		public Criteria andMemaddressIsNotNull() {
			addCriterion("memaddress is not null");
			return (Criteria) this;
		}

		public Criteria andMemaddressEqualTo(String value) {
			addCriterion("memaddress =", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressNotEqualTo(String value) {
			addCriterion("memaddress <>", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressGreaterThan(String value) {
			addCriterion("memaddress >", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressGreaterThanOrEqualTo(String value) {
			addCriterion("memaddress >=", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressLessThan(String value) {
			addCriterion("memaddress <", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressLessThanOrEqualTo(String value) {
			addCriterion("memaddress <=", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressLike(String value) {
			addCriterion("memaddress like", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressNotLike(String value) {
			addCriterion("memaddress not like", value, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressIn(List<String> values) {
			addCriterion("memaddress in", values, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressNotIn(List<String> values) {
			addCriterion("memaddress not in", values, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressBetween(String value1, String value2) {
			addCriterion("memaddress between", value1, value2, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemaddressNotBetween(String value1, String value2) {
			addCriterion("memaddress not between", value1, value2, "memaddress");
			return (Criteria) this;
		}

		public Criteria andMemgenderIsNull() {
			addCriterion("memgender is null");
			return (Criteria) this;
		}

		public Criteria andMemgenderIsNotNull() {
			addCriterion("memgender is not null");
			return (Criteria) this;
		}

		public Criteria andMemgenderEqualTo(String value) {
			addCriterion("memgender =", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderNotEqualTo(String value) {
			addCriterion("memgender <>", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderGreaterThan(String value) {
			addCriterion("memgender >", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderGreaterThanOrEqualTo(String value) {
			addCriterion("memgender >=", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderLessThan(String value) {
			addCriterion("memgender <", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderLessThanOrEqualTo(String value) {
			addCriterion("memgender <=", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderLike(String value) {
			addCriterion("memgender like", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderNotLike(String value) {
			addCriterion("memgender not like", value, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderIn(List<String> values) {
			addCriterion("memgender in", values, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderNotIn(List<String> values) {
			addCriterion("memgender not in", values, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderBetween(String value1, String value2) {
			addCriterion("memgender between", value1, value2, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemgenderNotBetween(String value1, String value2) {
			addCriterion("memgender not between", value1, value2, "memgender");
			return (Criteria) this;
		}

		public Criteria andMemnameIsNull() {
			addCriterion("memname is null");
			return (Criteria) this;
		}

		public Criteria andMemnameIsNotNull() {
			addCriterion("memname is not null");
			return (Criteria) this;
		}

		public Criteria andMemnameEqualTo(String value) {
			addCriterion("memname =", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameNotEqualTo(String value) {
			addCriterion("memname <>", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameGreaterThan(String value) {
			addCriterion("memname >", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameGreaterThanOrEqualTo(String value) {
			addCriterion("memname >=", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameLessThan(String value) {
			addCriterion("memname <", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameLessThanOrEqualTo(String value) {
			addCriterion("memname <=", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameLike(String value) {
			addCriterion("memname like", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameNotLike(String value) {
			addCriterion("memname not like", value, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameIn(List<String> values) {
			addCriterion("memname in", values, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameNotIn(List<String> values) {
			addCriterion("memname not in", values, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameBetween(String value1, String value2) {
			addCriterion("memname between", value1, value2, "memname");
			return (Criteria) this;
		}

		public Criteria andMemnameNotBetween(String value1, String value2) {
			addCriterion("memname not between", value1, value2, "memname");
			return (Criteria) this;
		}

		public Criteria andMembirthdayIsNull() {
			addCriterion("membirthday is null");
			return (Criteria) this;
		}

		public Criteria andMembirthdayIsNotNull() {
			addCriterion("membirthday is not null");
			return (Criteria) this;
		}

		public Criteria andMembirthdayEqualTo(String value) {
			addCriterion("membirthday =", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayNotEqualTo(String value) {
			addCriterion("membirthday <>", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayGreaterThan(String value) {
			addCriterion("membirthday >", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayGreaterThanOrEqualTo(String value) {
			addCriterion("membirthday >=", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayLessThan(String value) {
			addCriterion("membirthday <", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayLessThanOrEqualTo(String value) {
			addCriterion("membirthday <=", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayLike(String value) {
			addCriterion("membirthday like", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayNotLike(String value) {
			addCriterion("membirthday not like", value, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayIn(List<String> values) {
			addCriterion("membirthday in", values, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayNotIn(List<String> values) {
			addCriterion("membirthday not in", values, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayBetween(String value1, String value2) {
			addCriterion("membirthday between", value1, value2, "membirthday");
			return (Criteria) this;
		}

		public Criteria andMembirthdayNotBetween(String value1, String value2) {
			addCriterion("membirthday not between", value1, value2,
					"membirthday");
			return (Criteria) this;
		}

		public Criteria andMempictureIsNull() {
			addCriterion("mempicture is null");
			return (Criteria) this;
		}

		public Criteria andMempictureIsNotNull() {
			addCriterion("mempicture is not null");
			return (Criteria) this;
		}

		public Criteria andMempictureEqualTo(String value) {
			addCriterion("mempicture =", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureNotEqualTo(String value) {
			addCriterion("mempicture <>", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureGreaterThan(String value) {
			addCriterion("mempicture >", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureGreaterThanOrEqualTo(String value) {
			addCriterion("mempicture >=", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureLessThan(String value) {
			addCriterion("mempicture <", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureLessThanOrEqualTo(String value) {
			addCriterion("mempicture <=", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureLike(String value) {
			addCriterion("mempicture like", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureNotLike(String value) {
			addCriterion("mempicture not like", value, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureIn(List<String> values) {
			addCriterion("mempicture in", values, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureNotIn(List<String> values) {
			addCriterion("mempicture not in", values, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureBetween(String value1, String value2) {
			addCriterion("mempicture between", value1, value2, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMempictureNotBetween(String value1, String value2) {
			addCriterion("mempicture not between", value1, value2, "mempicture");
			return (Criteria) this;
		}

		public Criteria andMemdateIsNull() {
			addCriterion("memdate is null");
			return (Criteria) this;
		}

		public Criteria andMemdateIsNotNull() {
			addCriterion("memdate is not null");
			return (Criteria) this;
		}

		public Criteria andMemdateEqualTo(Date value) {
			addCriterion("memdate =", value, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateNotEqualTo(Date value) {
			addCriterion("memdate <>", value, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateGreaterThan(Date value) {
			addCriterion("memdate >", value, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateGreaterThanOrEqualTo(Date value) {
			addCriterion("memdate >=", value, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateLessThan(Date value) {
			addCriterion("memdate <", value, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateLessThanOrEqualTo(Date value) {
			addCriterion("memdate <=", value, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateIn(List<Date> values) {
			addCriterion("memdate in", values, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateNotIn(List<Date> values) {
			addCriterion("memdate not in", values, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateBetween(Date value1, Date value2) {
			addCriterion("memdate between", value1, value2, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemdateNotBetween(Date value1, Date value2) {
			addCriterion("memdate not between", value1, value2, "memdate");
			return (Criteria) this;
		}

		public Criteria andMemipIsNull() {
			addCriterion("memip is null");
			return (Criteria) this;
		}

		public Criteria andMemipIsNotNull() {
			addCriterion("memip is not null");
			return (Criteria) this;
		}

		public Criteria andMemipEqualTo(String value) {
			addCriterion("memip =", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipNotEqualTo(String value) {
			addCriterion("memip <>", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipGreaterThan(String value) {
			addCriterion("memip >", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipGreaterThanOrEqualTo(String value) {
			addCriterion("memip >=", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipLessThan(String value) {
			addCriterion("memip <", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipLessThanOrEqualTo(String value) {
			addCriterion("memip <=", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipLike(String value) {
			addCriterion("memip like", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipNotLike(String value) {
			addCriterion("memip not like", value, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipIn(List<String> values) {
			addCriterion("memip in", values, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipNotIn(List<String> values) {
			addCriterion("memip not in", values, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipBetween(String value1, String value2) {
			addCriterion("memip between", value1, value2, "memip");
			return (Criteria) this;
		}

		public Criteria andMemipNotBetween(String value1, String value2) {
			addCriterion("memip not between", value1, value2, "memip");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table members
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table members
     *
     * @mbggenerated do_not_delete_during_merge Mon Jun 02 11:29:14 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}