package klutch.hitter.com.model;

import java.util.Date;

public class Swboard {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLENUMBER
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private Integer articlenumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLESUBJECT
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String articlesubject;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLECONTENT
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String articlecontent;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLETIME
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private Date articletime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLEUSERID
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String articleuserid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLEUSERIP
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String articleuserip;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.articlereadcnt
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private Integer articlereadcnt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column swboard.ARTICLEPICTUREPATH
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	private String articlepicturepath;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLENUMBER
	 * @return  the value of swboard.ARTICLENUMBER
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Integer getArticlenumber() {
		return articlenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLENUMBER
	 * @param articlenumber  the value for swboard.ARTICLENUMBER
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticlenumber(Integer articlenumber) {
		this.articlenumber = articlenumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLESUBJECT
	 * @return  the value of swboard.ARTICLESUBJECT
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getArticlesubject() {
		return articlesubject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLESUBJECT
	 * @param articlesubject  the value for swboard.ARTICLESUBJECT
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticlesubject(String articlesubject) {
		this.articlesubject = articlesubject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLECONTENT
	 * @return  the value of swboard.ARTICLECONTENT
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getArticlecontent() {
		return articlecontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLECONTENT
	 * @param articlecontent  the value for swboard.ARTICLECONTENT
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticlecontent(String articlecontent) {
		this.articlecontent = articlecontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLETIME
	 * @return  the value of swboard.ARTICLETIME
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Date getArticletime() {
		return articletime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLETIME
	 * @param articletime  the value for swboard.ARTICLETIME
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticletime(Date articletime) {
		this.articletime = articletime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLEUSERID
	 * @return  the value of swboard.ARTICLEUSERID
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getArticleuserid() {
		return articleuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLEUSERID
	 * @param articleuserid  the value for swboard.ARTICLEUSERID
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticleuserid(String articleuserid) {
		this.articleuserid = articleuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLEUSERIP
	 * @return  the value of swboard.ARTICLEUSERIP
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getArticleuserip() {
		return articleuserip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLEUSERIP
	 * @param articleuserip  the value for swboard.ARTICLEUSERIP
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticleuserip(String articleuserip) {
		this.articleuserip = articleuserip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.articlereadcnt
	 * @return  the value of swboard.articlereadcnt
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Integer getArticlereadcnt() {
		return articlereadcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.articlereadcnt
	 * @param articlereadcnt  the value for swboard.articlereadcnt
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticlereadcnt(Integer articlereadcnt) {
		this.articlereadcnt = articlereadcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column swboard.ARTICLEPICTUREPATH
	 * @return  the value of swboard.ARTICLEPICTUREPATH
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getArticlepicturepath() {
		return articlepicturepath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column swboard.ARTICLEPICTUREPATH
	 * @param articlepicturepath  the value for swboard.ARTICLEPICTUREPATH
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setArticlepicturepath(String articlepicturepath) {
		this.articlepicturepath = articlepicturepath;
	}

	public String getSearch() {
		return search;
	}

	public void setSearch(String search) {
		this.search = search;
	}

	public String getMempicture() {
		return mempicture;
	}

	public void setMempicture(String mempicture) {
		this.mempicture = mempicture;
	}

	public int getCnum() {
		return cnum;
	}

	public void setCnum(int cnum) {
		this.cnum = cnum;
	}

	private String search;
	
	private String mempicture;
	
	private int cnum;
	
}