package klutch.hitter.com.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SwboardExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public SwboardExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andArticlenumberIsNull() {
			addCriterion("ARTICLENUMBER is null");
			return (Criteria) this;
		}

		public Criteria andArticlenumberIsNotNull() {
			addCriterion("ARTICLENUMBER is not null");
			return (Criteria) this;
		}

		public Criteria andArticlenumberEqualTo(Integer value) {
			addCriterion("ARTICLENUMBER =", value, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberNotEqualTo(Integer value) {
			addCriterion("ARTICLENUMBER <>", value, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberGreaterThan(Integer value) {
			addCriterion("ARTICLENUMBER >", value, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("ARTICLENUMBER >=", value, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberLessThan(Integer value) {
			addCriterion("ARTICLENUMBER <", value, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberLessThanOrEqualTo(Integer value) {
			addCriterion("ARTICLENUMBER <=", value, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberIn(List<Integer> values) {
			addCriterion("ARTICLENUMBER in", values, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberNotIn(List<Integer> values) {
			addCriterion("ARTICLENUMBER not in", values, "articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberBetween(Integer value1, Integer value2) {
			addCriterion("ARTICLENUMBER between", value1, value2,
					"articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlenumberNotBetween(Integer value1,
				Integer value2) {
			addCriterion("ARTICLENUMBER not between", value1, value2,
					"articlenumber");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectIsNull() {
			addCriterion("ARTICLESUBJECT is null");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectIsNotNull() {
			addCriterion("ARTICLESUBJECT is not null");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectEqualTo(String value) {
			addCriterion("ARTICLESUBJECT =", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectNotEqualTo(String value) {
			addCriterion("ARTICLESUBJECT <>", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectGreaterThan(String value) {
			addCriterion("ARTICLESUBJECT >", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectGreaterThanOrEqualTo(String value) {
			addCriterion("ARTICLESUBJECT >=", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectLessThan(String value) {
			addCriterion("ARTICLESUBJECT <", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectLessThanOrEqualTo(String value) {
			addCriterion("ARTICLESUBJECT <=", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectLike(String value) {
			addCriterion("ARTICLESUBJECT like", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectNotLike(String value) {
			addCriterion("ARTICLESUBJECT not like", value, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectIn(List<String> values) {
			addCriterion("ARTICLESUBJECT in", values, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectNotIn(List<String> values) {
			addCriterion("ARTICLESUBJECT not in", values, "articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectBetween(String value1, String value2) {
			addCriterion("ARTICLESUBJECT between", value1, value2,
					"articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlesubjectNotBetween(String value1, String value2) {
			addCriterion("ARTICLESUBJECT not between", value1, value2,
					"articlesubject");
			return (Criteria) this;
		}

		public Criteria andArticlecontentIsNull() {
			addCriterion("ARTICLECONTENT is null");
			return (Criteria) this;
		}

		public Criteria andArticlecontentIsNotNull() {
			addCriterion("ARTICLECONTENT is not null");
			return (Criteria) this;
		}

		public Criteria andArticlecontentEqualTo(String value) {
			addCriterion("ARTICLECONTENT =", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentNotEqualTo(String value) {
			addCriterion("ARTICLECONTENT <>", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentGreaterThan(String value) {
			addCriterion("ARTICLECONTENT >", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentGreaterThanOrEqualTo(String value) {
			addCriterion("ARTICLECONTENT >=", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentLessThan(String value) {
			addCriterion("ARTICLECONTENT <", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentLessThanOrEqualTo(String value) {
			addCriterion("ARTICLECONTENT <=", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentLike(String value) {
			addCriterion("ARTICLECONTENT like", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentNotLike(String value) {
			addCriterion("ARTICLECONTENT not like", value, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentIn(List<String> values) {
			addCriterion("ARTICLECONTENT in", values, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentNotIn(List<String> values) {
			addCriterion("ARTICLECONTENT not in", values, "articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentBetween(String value1, String value2) {
			addCriterion("ARTICLECONTENT between", value1, value2,
					"articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticlecontentNotBetween(String value1, String value2) {
			addCriterion("ARTICLECONTENT not between", value1, value2,
					"articlecontent");
			return (Criteria) this;
		}

		public Criteria andArticletimeIsNull() {
			addCriterion("ARTICLETIME is null");
			return (Criteria) this;
		}

		public Criteria andArticletimeIsNotNull() {
			addCriterion("ARTICLETIME is not null");
			return (Criteria) this;
		}

		public Criteria andArticletimeEqualTo(Date value) {
			addCriterion("ARTICLETIME =", value, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeNotEqualTo(Date value) {
			addCriterion("ARTICLETIME <>", value, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeGreaterThan(Date value) {
			addCriterion("ARTICLETIME >", value, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeGreaterThanOrEqualTo(Date value) {
			addCriterion("ARTICLETIME >=", value, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeLessThan(Date value) {
			addCriterion("ARTICLETIME <", value, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeLessThanOrEqualTo(Date value) {
			addCriterion("ARTICLETIME <=", value, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeIn(List<Date> values) {
			addCriterion("ARTICLETIME in", values, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeNotIn(List<Date> values) {
			addCriterion("ARTICLETIME not in", values, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeBetween(Date value1, Date value2) {
			addCriterion("ARTICLETIME between", value1, value2, "articletime");
			return (Criteria) this;
		}

		public Criteria andArticletimeNotBetween(Date value1, Date value2) {
			addCriterion("ARTICLETIME not between", value1, value2,
					"articletime");
			return (Criteria) this;
		}

		public Criteria andArticleuseridIsNull() {
			addCriterion("ARTICLEUSERID is null");
			return (Criteria) this;
		}

		public Criteria andArticleuseridIsNotNull() {
			addCriterion("ARTICLEUSERID is not null");
			return (Criteria) this;
		}

		public Criteria andArticleuseridEqualTo(String value) {
			addCriterion("ARTICLEUSERID =", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridNotEqualTo(String value) {
			addCriterion("ARTICLEUSERID <>", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridGreaterThan(String value) {
			addCriterion("ARTICLEUSERID >", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridGreaterThanOrEqualTo(String value) {
			addCriterion("ARTICLEUSERID >=", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridLessThan(String value) {
			addCriterion("ARTICLEUSERID <", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridLessThanOrEqualTo(String value) {
			addCriterion("ARTICLEUSERID <=", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridLike(String value) {
			addCriterion("ARTICLEUSERID like", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridNotLike(String value) {
			addCriterion("ARTICLEUSERID not like", value, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridIn(List<String> values) {
			addCriterion("ARTICLEUSERID in", values, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridNotIn(List<String> values) {
			addCriterion("ARTICLEUSERID not in", values, "articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridBetween(String value1, String value2) {
			addCriterion("ARTICLEUSERID between", value1, value2,
					"articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseridNotBetween(String value1, String value2) {
			addCriterion("ARTICLEUSERID not between", value1, value2,
					"articleuserid");
			return (Criteria) this;
		}

		public Criteria andArticleuseripIsNull() {
			addCriterion("ARTICLEUSERIP is null");
			return (Criteria) this;
		}

		public Criteria andArticleuseripIsNotNull() {
			addCriterion("ARTICLEUSERIP is not null");
			return (Criteria) this;
		}

		public Criteria andArticleuseripEqualTo(String value) {
			addCriterion("ARTICLEUSERIP =", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripNotEqualTo(String value) {
			addCriterion("ARTICLEUSERIP <>", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripGreaterThan(String value) {
			addCriterion("ARTICLEUSERIP >", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripGreaterThanOrEqualTo(String value) {
			addCriterion("ARTICLEUSERIP >=", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripLessThan(String value) {
			addCriterion("ARTICLEUSERIP <", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripLessThanOrEqualTo(String value) {
			addCriterion("ARTICLEUSERIP <=", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripLike(String value) {
			addCriterion("ARTICLEUSERIP like", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripNotLike(String value) {
			addCriterion("ARTICLEUSERIP not like", value, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripIn(List<String> values) {
			addCriterion("ARTICLEUSERIP in", values, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripNotIn(List<String> values) {
			addCriterion("ARTICLEUSERIP not in", values, "articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripBetween(String value1, String value2) {
			addCriterion("ARTICLEUSERIP between", value1, value2,
					"articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticleuseripNotBetween(String value1, String value2) {
			addCriterion("ARTICLEUSERIP not between", value1, value2,
					"articleuserip");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntIsNull() {
			addCriterion("articlereadcnt is null");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntIsNotNull() {
			addCriterion("articlereadcnt is not null");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntEqualTo(Integer value) {
			addCriterion("articlereadcnt =", value, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntNotEqualTo(Integer value) {
			addCriterion("articlereadcnt <>", value, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntGreaterThan(Integer value) {
			addCriterion("articlereadcnt >", value, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntGreaterThanOrEqualTo(Integer value) {
			addCriterion("articlereadcnt >=", value, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntLessThan(Integer value) {
			addCriterion("articlereadcnt <", value, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntLessThanOrEqualTo(Integer value) {
			addCriterion("articlereadcnt <=", value, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntIn(List<Integer> values) {
			addCriterion("articlereadcnt in", values, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntNotIn(List<Integer> values) {
			addCriterion("articlereadcnt not in", values, "articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntBetween(Integer value1, Integer value2) {
			addCriterion("articlereadcnt between", value1, value2,
					"articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlereadcntNotBetween(Integer value1,
				Integer value2) {
			addCriterion("articlereadcnt not between", value1, value2,
					"articlereadcnt");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathIsNull() {
			addCriterion("ARTICLEPICTUREPATH is null");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathIsNotNull() {
			addCriterion("ARTICLEPICTUREPATH is not null");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathEqualTo(String value) {
			addCriterion("ARTICLEPICTUREPATH =", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathNotEqualTo(String value) {
			addCriterion("ARTICLEPICTUREPATH <>", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathGreaterThan(String value) {
			addCriterion("ARTICLEPICTUREPATH >", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathGreaterThanOrEqualTo(String value) {
			addCriterion("ARTICLEPICTUREPATH >=", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathLessThan(String value) {
			addCriterion("ARTICLEPICTUREPATH <", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathLessThanOrEqualTo(String value) {
			addCriterion("ARTICLEPICTUREPATH <=", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathLike(String value) {
			addCriterion("ARTICLEPICTUREPATH like", value, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathNotLike(String value) {
			addCriterion("ARTICLEPICTUREPATH not like", value,
					"articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathIn(List<String> values) {
			addCriterion("ARTICLEPICTUREPATH in", values, "articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathNotIn(List<String> values) {
			addCriterion("ARTICLEPICTUREPATH not in", values,
					"articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathBetween(String value1,
				String value2) {
			addCriterion("ARTICLEPICTUREPATH between", value1, value2,
					"articlepicturepath");
			return (Criteria) this;
		}

		public Criteria andArticlepicturepathNotBetween(String value1,
				String value2) {
			addCriterion("ARTICLEPICTUREPATH not between", value1, value2,
					"articlepicturepath");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table swboard
	 * @mbggenerated  Mon Aug 11 17:33:02 KST 2014
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table swboard
     *
     * @mbggenerated do_not_delete_during_merge Thu May 29 16:52:07 KST 2014
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}