package klutch.hitter.com.dao;


import java.util.List;

import klutch.hitter.com.model.Comment;
import klutch.hitter.com.model.Swboard;
import klutch.hitter.com.model.SwboardExample;

import org.apache.ibatis.annotations.Param;

public interface SwboardMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int countByExample(SwboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int deleteByExample(SwboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int deleteByPrimaryKey(Integer articlenumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int insert(Swboard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int insertSelective(Swboard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	List<Swboard> selectByExample(SwboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	Swboard selectByPrimaryKey(Integer articlenumber);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int updateByExampleSelective(@Param("record") Swboard record,
			@Param("example") SwboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int updateByExample(@Param("record") Swboard record,
			@Param("example") SwboardExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int updateByPrimaryKeySelective(Swboard record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table swboard
	 * @mbggenerated  Mon Jun 02 16:54:14 KST 2014
	 */
	int updateByPrimaryKey(Swboard record);

	int getCount();
    
    List<Swboard> getSwboardList();
    
    List<Swboard> getSwboardListBySubject(String search);
    List<Swboard> getSwboardListByContent(String search);
    List<Swboard> getSwboardListByUserid(String search);
    List<Comment> getCnoList();
    void insertReadCnt(@Param("cnt")int cnt,@Param("no") int no);
    
}